### ISSUE TITLE
Error: moduleId should be a string in "SatCalendar"

### ISSUE THREAD

**Issue by tajro** [SaturnTeam/saturn-datepicker#22]
Hello,
I'm trying to use the latest version of your datepicker, but my Chrome is giving me this error:
**Error: moduleId should be a string in "SatCalendar"**
The error occurs even if I don't add <sat-datepicker> into template,
I only imported SatDatepickerModule...

@NgModule({
    imports: [
        SatDatepickerModule,
        SatNativeDateModule,
...

I'm using:
"@angular/material": "6.0.1",
"saturn-datepicker": "^6.0.1",

Thanks!

**Comment by SaturnTeam** [comment]
maybe you are using an old version of angular?

**Comment by tajro** [comment]
I'm using angular 6.0.0 :-/

"@angular/animations": "6.0.0",
    "@angular/cdk": "6.0.1",
    "@angular/common": "6.0.0",
    "@angular/compiler": "6.0.0",
    "@angular/core": "6.0.0",
    "@angular/forms": "6.0.0",
    "@angular/http": "6.0.0",
    "@angular/material": "6.0.1",
    "@angular/platform-browser": "6.0.0",
    "@angular/platform-browser-dynamic": "6.0.0",
    "@angular/platform-server": "6.0.0",
    "@angular/router": "6.0.0",
    "@ng-bootstrap/ng-bootstrap": "2.0.0",
...

**Comment by SaturnTeam** [comment]
maybe an old version of angular-cli?

**Comment by Skullpluggery** [comment]
I am getting this issue as well, I am on Angular 9.

**Comment by Skullpluggery** [comment]
removing `moduleId: module.id` in all components solve the issue as new Angular doesn't need it anymore.

**Comment by dsebastien** [comment]
Same issue here, using Angular 9

**Comment by ThibaudAV** [comment]
Same issue, using Angular 9 and storybook 
@SaturnTeam what do you think about removing the `moduleId: module.id` that doesn't seem necessary anymore?

**Comment by WillGeller** [comment]
@SaturnTeam It sounds like @ThibaudAV's change made it into `master` but will not be released on NPM anytime soon (due to the ng-packgr issue you described). You [mentioned](https://github.com/SaturnTeam/saturn-datepicker/pull/160) the next release will be for Angular 10 anyway but I would argue that the value of this library lies in its compatibility with versions of Angular 7-9. With v10 of Angular Material it looks like they have created a date range function in the official library https://material.angular.io/components/datepicker/overview#date-range-input-forms-integration. The reality is teams on older versions of Angular or AngularJS/Angular hybrid and being upgraded (there are many) will not be able to make the switch to 10 overnight.

This library brings a lot of value to the teams that are on Angular <10 and I thank you for being first to support the community with it. Removing `moduleId: module.id` seems like a minor release that could be sent out to the community in a patch release. Regardless I was able to use this solution to patch the src code from this library after installing https://stackoverflow.com/a/62567504
