### ISSUE TITLE
Styles dont apply when using it in the component scss file

### ISSUE THREAD

**Issue by MuhammadElhrz** [SaturnTeam/saturn-datepicker#42]
I am using Angular 6 and i am using the datepicker in a component
I am putting the styles of the datepicker in the compoenent scss file but it doesnt applu correctly
It applies correctly when putting it in the general style.scss file
Here is the code:
@import '~@angular/material/theming';
@import '../../../../theme.scss'; The file that contains the app theme
@import '~saturn-datepicker/theming';
@include sat-datepicker-theme($theme);

**Comment by daveo1001** [comment]
This is a result of angular scoping. [https://angular.io/guide/component-styles](https://angular.io/guide/component-styles)

If you want to style the datepicker component from within a component you should look into `::ng-deep`. but watch out because that has caveats as well. [https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep)
